# QKD 파라미터 설정 파일

# Detection parameters
detection:
  eta_d: 0.0212350696577481              # detection efficiency of single-photon detector (%)
  Y_0: 8.70602087830484E-06                  # dark count rate
  e_d: 0.0449732792240126                    # misalignment rate

# Fiber parameters
fiber:
  alpha: 0.192740346640696                  # attenuation coefficient of single-mode fiber

# Error correction parameters
error_correction:
  zeta: 1.15454749016213                   # efficiency of error correction
  e_0: 0.436680901970686                      # error rate of the background (ref 23)

# Security parameters
security:
  eps_sec: 1.64804464279789E-11               # security parameter
  eps_cor: 1.40779231399723E-15                # correctness parameter

# System parameters
system:
  N: 7309539835.91292                      # number of optical pulses sent by Alice
  Lambda: null                    # probability of bit value 1 observed in Xk

# Reference data for comparison
reference:
        # L =    0,      10,     20,     30,     40,     50,     60,     70,     80,     90,    100,    110
  skr_values: [3.0e-3, 1.7e-3, 9.0e-4, 5.0e-4, 2.9e-4, 1.7e-4, 8.0e-5, 4.0e-5, 1.9e-5, 8.0e-6, 3.0e-6, 3.0e-7]
  optimized : [0.0e-9, 0.0e-9, 0.0e-9, 0.0e-9, 0.0e-9, 0.0e-9, 0.0e-9, 0.0e-9, 0.0e-9, 0.0e-9, 9.883606e-06, 0.0e-9]
