# QKD 파라미터 설정 파일

detection:
  eta_d: 0.045                    
  Y_0: 1.7e-6                   
  e_d: 0.033                     

fiber:
  alpha: 0.21                   

error_correction:
  zeta: 1.22                      
  e_0: 0.5                       

security:
  eps_sec: 1.0e-10              
  eps_cor: 1.0e-15               

system:
  N: 1.0e10                    
  Lambda: null                   

reference:
        # L =    0,      10,     20,     30,     40,     50,     60,     70,     80,     90,    100,    110
  skr_values: [3.0e-3, 1.7e-3, 9.0e-4, 5.0e-4, 2.9e-4, 1.7e-4, 8.0e-5, 4.0e-5, 1.9e-5, 8.0e-6, 3.0e-6, 3.0e-7]
  optimized : [0.0e-9, 0.0e-9, 0.0e-9, 0.0e-9, 0.0e-9, 0.0e-9, 0.0e-9, 0.0e-9, 0.0e-9, 0.0e-9, 9.883606e-06, 0.0e-9]
